In [1]:
# 忽略警告訊息
import warnings
warnings.filterwarnings("ignore")

# 匯入必要的套件
import matplotlib.pyplot as plt

# 使用 fivethirtyeight 風格，讓圖表更美觀
# plt.style.use('fivethirtyeight')

# 設定字型，確保中文能正常顯示
plt.rcParams["font.family"] = "sans-serif"
plt.rcParams["font.sans-serif"] = [
    "Microsoft JhengHei",
    "Microsoft YaHei",
    "SimHei",
    "Arial Unicode MS",
    "DejaVu Sans"
]

# 設定數學字型，確保負號能正常顯示
plt.rcParams["axes.unicode_minus"] = False
plt.rcParams["mathtext.fontset"] = "dejavusans"

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("./ex1.csv")

# 數值特徵
numeric_features = ["HP", "Attack", "Defense", "SpecialAtk", "SpecialDef", "Speed"]

# 類別特徵
categorical_features = ["Type1", "Type2", "Generation"]

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Number      168 non-null    int64
 1   Name        168 non-null    str
 2   Type1       168 non-null    str
 3   Type2       79 non-null     str
 4   HP          166 non-null    float64
 5   Attack      168 non-null    int64
 6   Defense     168 non-null    int64
 7   SpecialAtk  168 non-null    int64
 8   SpecialDef  168 non-null    int64
 9   Speed       168 non-null    int64
 10  Generation  168 non-null    int64
 11  Legendary   168 non-null    bool
dtypes: bool(1), float64(1), int64(7), str(3)
memory usage: 14.7 KB

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer

numeric_data = data.loc[:, numeric_features].copy()
numeric_data_without_missing = numeric_data.dropna(axis=0).copy()

standard_scaler = StandardScaler()
standard_scaled = standard_scaler.fit_transform(numeric_data_without_missing)
standard_scaled = pd.DataFrame(
    standard_scaled, 
    columns=numeric_features
)
display(standard_scaled)

minmax_scaler = MinMaxScaler()
minmax_scaled = minmax_scaler.fit_transform(numeric_data_without_missing)
minmax_scaled = pd.DataFrame(
    minmax_scaled, 
    columns=numeric_features
)
display(minmax_scaled)

robust_scaler = RobustScaler()
robust_scaled = robust_scaler.fit_transform(numeric_data_without_missing)
robust_scaled = pd.DataFrame(
    robust_scaled, 
    columns=numeric_features
)
display(robust_scaled)

normalizer = Normalizer(norm="l2")
normalized = normalizer.fit_transform(numeric_data_without_missing)
normalized = pd.DataFrame(
    normalized, 
    columns=numeric_features
)
display(normalized)

           HP    Attack   Defense  SpecialAtk  SpecialDef     Speed
0   -0.741717 -0.901689 -0.765593   -0.198609   -0.160858 -0.932334
1   -0.207320 -0.477573 -0.275310    0.238260    0.429035 -0.425343
2    0.505209  0.174914  0.425095    0.820753    1.215559  0.250645
3    0.505209  0.762151  1.825903    1.461494    2.002083  0.250645
4   -0.955475 -0.803816 -0.975714   -0.344232   -0.750752 -0.256346
..        ...       ...       ...         ...         ...       ...
161  0.897100  1.871378  0.845337    0.820753    1.215559  0.250645
162  1.431496  1.088394  0.670236    2.393482    0.822297  1.940614
163  1.431496  3.698340  1.020438    2.393482    1.215559  1.940614
164  1.431496  2.393367 -0.030168    3.558467    2.002083  2.278608
165  1.217738  0.762151  1.020438    0.820753    1.215559  0.926633

[166 rows x 6 columns]

           HP    Attack   Defense  SpecialAtk  SpecialDef     Speed
0    0.145833  0.237838  0.251429    0.279330    0.409091  0.222222
1    0.208333  0.308108  0.331429    0.363128    0.545455  0.333333
2    0.291667  0.416216  0.445714    0.474860    0.727273  0.481481
3    0.291667  0.513514  0.674286    0.597765    0.909091  0.481481
4    0.120833  0.254054  0.217143    0.251397    0.272727  0.370370
..        ...       ...       ...         ...         ...       ...
161  0.337500  0.697297  0.514286    0.474860    0.727273  0.481481
162  0.400000  0.567568  0.485714    0.776536    0.636364  0.851852
163  0.400000  1.000000  0.542857    0.776536    0.727273  0.851852
164  0.400000  0.783784  0.371429    1.000000    0.909091  0.925926
165  0.375000  0.513514  0.542857    0.474860    0.727273  0.629630

[166 rows x 6 columns]

           HP  Attack   Defense  SpecialAtk  SpecialDef     Speed
0   -0.507463  -0.650 -0.485714        0.00   -0.142857 -0.591716
1   -0.059701  -0.325 -0.085714        0.30    0.285714 -0.236686
2    0.537313   0.175  0.485714        0.70    0.857143  0.236686
3    0.537313   0.625  1.628571        1.14    1.428571  0.236686
4   -0.686567  -0.575 -0.657143       -0.10   -0.571429 -0.118343
..        ...     ...       ...         ...         ...       ...
161  0.865672   1.475  0.828571        0.70    0.857143  0.236686
162  1.313433   0.875  0.685714        1.78    0.571429  1.420118
163  1.313433   2.875  0.971429        1.78    0.857143  1.420118
164  1.313433   1.875  0.114286        2.58    1.428571  1.656805
165  1.134328   0.625  0.971429        0.70    0.857143  0.710059

[166 rows x 6 columns]

           HP    Attack   Defense  SpecialAtk  SpecialDef     Speed
0    0.342109  0.372519  0.372519    0.494157    0.494157  0.342109
1    0.359772  0.371764  0.377761    0.479696    0.479696  0.359772
2    0.371339  0.380622  0.385264    0.464173    0.464173  0.371339
3    0.308577  0.385721  0.474437    0.470580    0.462865  0.308577
4    0.304548  0.406064  0.335784    0.468536    0.390446  0.507580
..        ...       ...       ...         ...         ...       ...
161  0.366465  0.539630  0.382573    0.402709    0.402709  0.322167
162  0.374411  0.388540  0.317896    0.543956    0.317896  0.459183
163  0.322619  0.578280  0.304358    0.468711    0.304358  0.395665
164  0.319208  0.451709  0.210797    0.584210    0.361367  0.421595
165  0.408248  0.408248  0.408248    0.408248    0.408248  0.408248

[166 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import LabelEncoder

category_data = data.copy()

type1_one_hot = pd.get_dummies(
    category_data["Type1"], 
    prefix="Type1", 
    dtype=int
)
type1_one_hot

label_encoder = LabelEncoder()
type1_label = label_encoder.fit_transform(category_data["Type1"])
type1_label = pd.DataFrame({
    "Type1": category_data["Type1"], 
    "Type1_label": type1_label
})

type1_label

       Type1  Type1_label
0      Grass            7
1      Grass            7
2      Grass            7
3      Grass            7
4       Fire            5
..       ...          ...
163  Psychic           12
164  Psychic           12
165  Psychic           12
166    Grass            7
167      Bug            0

[168 rows x 2 columns]

In [26]:
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer

missing_data = data.copy()

numeric_missing_data = missing_data.loc[:, numeric_features]
type2_imputer = SimpleImputer(strategy="constant", fill_value="NoType2")
type2_imputed = type2_imputer.fit_transform(missing_data.loc[:, ["Type2"]])
type2_imputed = pd.DataFrame(type2_imputed, columns=["Type2_imputed"])

type2_imputed

knn_imputer = KNNImputer(n_neighbors=3)
knn_imputed = knn_imputer.fit_transform(numeric_missing_data)
knn_imputed = pd.DataFrame(knn_imputed, columns=numeric_features)

knn_imputed

             HP  Attack  Defense  SpecialAtk  SpecialDef  Speed
0     45.000000    49.0     49.0        65.0        65.0   45.0
1     60.000000    62.0     63.0        80.0        80.0   60.0
2     80.000000    82.0     83.0       100.0       100.0   80.0
3     80.000000   100.0    123.0       122.0       120.0   80.0
4     39.000000    52.0     43.0        60.0        50.0   65.0
..          ...     ...      ...         ...         ...    ...
163  106.000000   190.0    100.0       154.0       100.0  130.0
164  106.000000   150.0     70.0       194.0       120.0  140.0
165  100.000000   100.0    100.0       100.0       100.0  100.0
166   69.666667    62.0     80.0        63.0        80.0   60.0
167   60.000000    35.0     50.0        55.0       110.0   85.0

[168 rows x 6 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

split_data = data.copy()

X = split_data.loc[:, numeric_features].copy()
y = split_data["Legendary"].astype(int).copy()

split_imputer = SimpleImputer(strategy="median")
X_filled = split_imputer.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_filled,
    y,
    test_size=0.25,
    random_state=0,
    stratify=y
)

split_scaler = StandardScaler()
X_train_scaled = split_scaler.fit_transform(X_train)
X_test_scaled = split_scaler.transform(X_test)

split_model = KNeighborsClassifier(n_neighbors=3)
split_model.fit(X_train_scaled, y_train)